### ISSUE TITLE
on pip install -r requirements command, errors appears!?

### ISSUE THREAD

**Issue by hassanayoub85** [seth814/Audio-Classification#1]
Hello,
I am trying your code, however I am facing an error, when running "pip install -r requirements" command it show an error in object-detection package as not found!

**Comment by seth814** [comment]
Looks like object-detection needs to be updated to 0.0.3. This will also cause tensorflow to upgrade to 1.14, but that should be okay.

**Comment by seth814** [comment]
Updated requirements.txt. Was able to install in fresh conda env.

**Comment by hassanayoub85** [comment]
Thx it works.
Any idea how to use it? there is no any description in the python files :(

**Comment by seth814** [comment]
https://youtu.be/Z7YM-HAz-IY
