### ISSUE TITLE
Clarification on TimeDistributed

### ISSUE THREAD

**Issue by M-Shahbaz-Khan** [seth814/Audio-Classification#13]
Hi,

I have a question about the TimeDistributed wrapper - I think I understand how it works, but I'm not sure. I would really appreciate if someone could check my understanding. The first 'real' layer of the 1D Conv model:

`x = TimeDistributed(layers.Conv1D(8, kernel_size=(4), activation='tanh'), name='td_conv_1d_tanh')(x)`

with input `100, 128, 1` yielding `40` trainable parameters and an output of `100, 125, 8`.

This makes sense to me as applying a 1D conv along the 128-shape frequency/melbin axis, for each of the 100 time bins, and learning filters weights/biases as it goes. I'm guessing the step size for the convolution is 1, which is why we get 125 on the output. For the LSTM:

`s = TimeDistributed(layers.Dense(64, activation='tanh'), name='td_dense_tanh')(x)`

with input `100, 128` yielding `8256` trainable parameters and output `100, 64`.

We have 64 nodes fully connected to the 128 frequencies, so we wind up with 128 * 64 + 64 = 8256 parameters. Then these are trained over each of the 100 time bins. Does that sound right?

Thanks a lot to Seth for the code and videos, they are very helpful.

**Comment by seth814** [comment]
It's been a while since I've actually done the math around trainable parameters, but looking at this it seems correct. Passing over time and building features around them while allowing a sense of time to be preserved into future layers. Numbers seem right to me.
