### ISSUE TITLE
clean.py being picky about WAV bit depth | ValueError: Unsupported bit depth: the wav file has 24-bit data

### ISSUE THREAD

**Issue by Ma5onic** [seth814/Audio-Classification#14]
I was attempting to use my sample and multitrack collections in order to train a model geared more towards electronic music by following your youtube posts from February. I made sure that I all my files were in WAV format (as suggested in the video) but scipy seems to be unable to process "high" bit depths. 
What would be the best way to convert my custom WAV files in in "wavfiles" folder to the appropriate bit depth (and/or sample rate)?

Output of `python clean.py`:
```
  0%|                                                                                       | 0/4 [00:00<?, ?it/s]
clean.py:27: WavFileWarning: Chunk (non-data) not understood, skipping it.
  rate, wav = wavfile.read(path)
  0%|                                                                                       | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "clean.py", line 128, in <module>
    split_wavs(args)
  File "clean.py", line 68, in split_wavs
    rate, wav = downsample_mono(src_fn, args.sr)
  File "clean.py", line 27, in downsample_mono
    rate, wav = wavfile.read(path)
  File "/home/myusername/anaconda3/lib/python3.7/site-packages/scipy/io/wavfile.py", line 298, in read
    "has {}-bit data.".format(bit_depth))
ValueError: Unsupported bit depth: the wav file has 24-bit data.
```

**Comment by seth814** [comment]
`ffprobe audio_file.wav`

Will show the metadata for an audio file.

I was able to convert 24 bit wav to 16 bit wav using:

`ffmpeg -i src.wav -c:a pcm_s16le dst.wav`

You will have to either run a bash script to convert all the files or make a script with python to call ffmpeg from command line to run on all the files.

**Comment by kledo-34** [comment]
I used wavio.read to read in all bit data types:
I added:
`    import wavio`

I changed downsample_mono() to:
`def downsample_mono(path, sr):
    try:
        data = wavio.read(path).data.T
    except:
        return False, False

    if data.shape[0] == 2:
        data = np.mean(data, axis=0)
    else:
        data = data[0]

    rate = wavio.read(path).rate

    wav = resample(data.astype(np.float32), rate, sr)
    wav = wav.astype(np.int16)

    return sr, wav`

Error exception is for wrong format tag which will throw an error once in a while, but not often. Therefor I added a continue in the second for loop of split_wavs():

after line 68:

`            if rate == False and wav == False:
                continue`

Greetings ;)

**Comment by Ma5onic** [comment]
@seth814,  I followed your instructions and here is where what I've done/discovered so far:
I made a bash file called 24to16.sh which was executed in every directory that contained WAV files to clean (within the "wavefiles" directory):
```bash
#!/bin/bash
for i in *.wav
    do name=`echo "$i" | cut -d'.' -f1`
    echo "$name"
    ffmpeg -y -i "$i" -c:a pcm_s16le "${name}.wav"
done
```

I noticed that songs with a space in the filename would not get converted properly, so I ran the following to get rid of any spaces:
```bash
for oldname in *; do newname=`echo $oldname | sed -e 's/ //g'`; mv "$oldname" "$newname"; done
```
I then executed 24to16.sh in every directory which contained files with problematic filenames.

When executed, `python clean.py` now outputs:
```
Traceback (most recent call last):
  File "clean.py", line 128, in <module>
    split_wavs(args)
  File "clean.py", line 68, in split_wavs
    rate, wav = downsample_mono(src_fn, args.sr)
  File "clean.py", line 28, in downsample_mono
    wav = resample(wav.astype(np.float32), rate, sr)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/librosa/core/audio.py", line 293, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "/home/myuser/anaconda3/envs/audio/lib/python3.7/site-packages/resampy/core.py", line 98, in resample
    'resample from {}->{}'.format(x.shape[axis], sr_orig, sr_new))
ValueError: Input signal length=2 is too small to resample from 44100->16000

```
I was able to bypass this error by changing the default sample rate (--sr) in "clean.py" to a value of 32000.

After fixing the filenames & changing the default sample rate, `python clean.py` now executes without without any errors.

**Comment by Ma5onic** [comment]
See issue #25 for final remarks
