### ISSUE TITLE
Overlapping window ??

### ISSUE THREAD

**Issue by RVT123123** [seth814/Audio-Classification#15]
You have taken a window frame as 1/10 of a sec if I am not wrong I also want to know what is the overlapping Window you have taken ?? because nowhere in your tutorials you have mentioned about overlapping window.

**Comment by seth814** [comment]
The calculation of the stft has an overlapping window. Taking a 1/10 second window was something I did in the older videos. The new ones use a 1 second interval for the data. They do not overlap.
