### ISSUE TITLE
NotADirectoryError when splitting wavfiles with split_wavs(args)

### ISSUE THREAD

**Issue by dawizell** [seth814/Audio-Classification#17]
Hi, thanks for the material and the videos. 
I am trying to run the clean.py script with my own audio files, but I get this error:

```
Traceback (most recent call last):
  File "clean.py", line 129, in <module>
    split_wavs(args)
  File "clean.py", line 66, in split_wavs
    for fn in tqdm(os.listdir(src_dir)):
NotADirectoryError: [Errno 20] Not a directory: 'wavfiles/.DS_Store'
```

I tried with the directory you provided, but after it iterates for 3 sub-folders I still get the same error:

```
100%|███████████████| 30/30 [00:05<00:00,  5.31it/s]
100%|███████████████| 30/30 [00:04<00:00,  6.84it/s]
100%|███████████████| 30/30 [00:06<00:00,  4.75it/s]
Traceback (most recent call last):
  File "clean.py", line 129, in <module>
    split_wavs(args)
  File "clean.py", line 66, in split_wavs
    for fn in tqdm(os.listdir(src_dir)):
NotADirectoryError: [Errno 20] Not a directory: 'wavfiles/.DS_Store'
```

**Comment by seth814** [comment]
You have a .DS_Store file in your wavfiles directory. The wavfiles directory should only have directories with wav files in them. .DS_Store is a file. It is hidden so you won't see it normally, but it is in fact there. Just remove it.

**Comment by dawizell** [comment]
Perfect, thanks!
