### ISSUE TITLE
Audio buffer is not Fortran-contiguous

### ISSUE THREAD

**Issue by adityanandgaokar** [seth814/Audio-Classification#18]
rate, wav = downsample_mono(wav_path[0], args.sr)

 wav = resample(wav.astype(np.float32), rate, sr)

raise ParameterError('Audio buffer is not Fortran-contiguous. '
librosa.util.exceptions.ParameterError: Audio buffer is not Fortran-contiguous. Use numpy.asfortranarray to ensure Fortran contiguity.

**Comment by seth814** [comment]
This should have been solved: `https://github.com/seth814/Audio-Classification/issues/16`

Can you `git pull` the latest commit and try again?

**Comment by adityanandgaokar** [comment]
Thank you seth. you are awesome.

**Comment by adityanandgaokar** [comment]
Thank you seth. you are awesome.
