### ISSUE TITLE
index_error

### ISSUE THREAD

**Issue by adityanandgaokar** [seth814/Audio-Classification#19]
FutureWarning: norm=1 behavior will change in librosa 0.8.0. To maintain forward compatibility, use norm='slaney' instead

labels = [self.labels[k] for k in indexes]
IndexError: index 7 is out of bounds for axis 0 with size 3

**Comment by seth814** [comment]
Can you print the len(labels) after line 79 of train.py?

Also maybe show a couple examples of labels although I don't think it matters.

**Comment by adityanandgaokar** [comment]
Do we have give specific path to this line 
        self.labels = labels
like we gave to this 
        self.wav_paths =('C:/Users/i00504285/Desktop/Aditya/Sound_Analysis/CSF48/wave_files/clean')

**Comment by adityanandgaokar** [comment]
> Can you print the len(labels) after line 79 of train.py?
> 
> Also maybe show a couple examples of labels although I don't think it matters.

Ya I did it shows  4  to me 

https://drive.google.com/drive/folders/1tdUN92kf6oDC3-h2eCh_IZjVMMLdC-OA?usp=sharing

above link where i uploaded all my files.

Thank you.

**Comment by seth814** [comment]
The issue is, len(labels) needs to be >= batch_size. So after you run clean.py, you will need at least 16 files if using a batch_size of 16. You're data size is too small for this type of network. You can reduce batch_size to 4 but the model will never be able to generalize to new data.

**Comment by adityanandgaokar** [comment]
Ok one quick question seth, If i will give 30 files in one class and as  you know i have 2 classes so batch_size = 16 will work for me or any other number will work for me??
