### ISSUE TITLE
IndexError: index 63 is out of bounds for axis 0 with size 57

### ISSUE THREAD

**Issue by adityanandgaokar** [seth814/Audio-Classification#21]
Hello seth as you said i need more files for this kind of network so now i have more than 30 files in one class and i have two classes but it gave me 

IndexError: index 63 is out of bounds for axis 0 with size 57
 this error so please help me here you can find all the regarding files of project :- 
[https://drive.google.com/drive/folders/1DretGkD66hQ0zV2Fwo8YzWwh0woNFS8X?usp=sharing](url)

**Comment by seth814** [comment]
I downloaded your data and tried it myself. After running clean.py, I got 1042 samples in no_water. 1020 samples in water. Ran train.py. Accuracy went to around 90% for train and val. Was not able to reproduce this error with sufficient data size.
