### ISSUE TITLE
valueError 

### ISSUE THREAD

**Issue by adityanandgaokar** [seth814/Audio-Classification#22]
X[i,] = wav.reshape(1, -1)
ValueError: could not broadcast input array from shape (1,3080192) into shape (1,16000)

please find files in attached link :- [https://drive.google.com/drive/folders/1hRpOLXArm0gP9QPB9RuYgeWNFQerkbuP?usp=sharing](url)

**Comment by seth814** [comment]
I've ran your data. It works just fine as long as you have two directories for each class in the wavfiles directory for example. water and no_water. This error suggests you did not clean your audio first and are passing several seconds of data.

**Comment by adityanandgaokar** [comment]
Ok, but seth i have cleaned my data the file which i have sent you, you can see clean directory where i have my data but one confusion is when i pass 
        self.wav_paths = wav_paths 
then i got 
 X[i,] = wav.reshape(1, -1)
ValueError: could not broadcast input array from shape (1,3424256) into shape (1,16000)

but when i pass :-
        self.wav_paths  = 
 ('C:/Users/i00504285/Desktop/Aditya/Sound_Analysis/CSF48/wave_files/clean')

where i have  my clean data then i got 
IndexError: index 56 is out of bounds for axis 0 with size 54
 the above error

**Comment by seth814** [comment]
wav_paths should be a list of file paths to all the wav files in the src_root from argparser at the bottom. The src_root should be your clean directory here. That second way of manually setting it to a directory is wrong. I think it's just looking in the wrong directory. Check your src_root.

**Comment by adityanandgaokar** [comment]
Ya it solved thank you, but i have one new issue which is:- 
tensorflow.python.framework.errors_impl.InvalidArgumentError:  logits and labels must be broadcastable: logits_size=[16,10] labels_size=[16,2] 

[[node loss/softmax_loss/softmax_cross_entropy_with_logits (defined at C:\Users\i00504285\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_distributed_function_4563]

Function call stack:
distributed_function.

why this happened and how to solve this?

**Comment by seth814** [comment]
It looks like you are using a model with the softmax output for 10 classes while you have 2 classes.

What file are you running that creates this error? line number?

**Comment by adityanandgaokar** [comment]
I solved it thank you 👍
