### ISSUE TITLE
TypeError: Value passed to parameter 'input' has DataType int16 not in list of allowed values: float16, bfloat16, float32, float64

### ISSUE THREAD

**Issue by adityanandgaokar** [seth814/Audio-Classification#23]
I got error on this line -
        y_pred = model.predict(X_batch)
please check and help me.
all files are available here :-
https://drive.google.com/drive/folders/1hRpOLXArm0gP9QPB9RuYgeWNFQerkbuP?usp=sharing

**Comment by seth814** [comment]
That seems weird. What tensorflow version are you running?

The solution to this would be in the line above: `X_batch = np.array(batch, dtype=np.float16)`

Seems weird that it wouldn't be able to cast the variable if it couldn't accept int16.

**Comment by adityanandgaokar** [comment]
Thank you seth
