### ISSUE TITLE
train.py: IndexError: index 9 is out of bounds for axis 1 with size 9

### ISSUE THREAD

**Issue by martindisley** [seth814/Audio-Classification#27]
Hi Seth

I'm working on an amended `clean.py` - one that will support other audio file types. 

I'm testing it with your `wavfiles` folder as a benchmark with the hope that I can reproduce the score I got before any changes. I've noticed it creates a few more files (differences in threshold for trimming i think), however, they are all still one second long and the file structure is identical (ie 10 classes named exactly as yours are).

running `train.py` returns the following:

`IndexError: index 9 is out of bounds for axis 1 with size 9`

I think the problem is with `wav_train, wav_val, label_train, label_val = train_test_split(wav_paths, labels, test_size=0.1, random_state=0)`. To look into it I added:

```
print(len(set(label_train)))
10
print(len(set(label_val)))
9
```
if I set `test_size=0.5` then I get:

```
print(len(set(label_train)))
10
print(len(set(label_val)))
10
```

Training then runs without error but the accuracy is about 10%

I'm really not sure what's going on here. I've listened to the audio files and looked at the spectrograms of files created by my `clean.py` and they seem very normal. They can be found [here](https://drive.google.com/file/d/1wVT3WqF7CVhCkYwYOUtH-dyQiv5U4Y13/view?usp=sharing), I'd be v grateful if you could try and reproduce this.

**Comment by martindisley** [comment]
I've since found that setting `random_state=1` in `train_test_split` solves the index error, but still i'm getting incredibly low accuracy.

**Comment by seth814** [comment]
Other people have had this error. I'm going to add a warning to handle instances where not all classes are present (due to low data size and random_state). It should allow the model to train even if classes are missing.

As for accuracy, I have no idea. When I run this repo using the default threshold of 20, I get 168 files for Acoustic_guitar. Running train.py with default settings on the cleaned audio, Accuracy starts at ~30 % after first epoch. Eventually the train / test split accuracy is ~95 / 80 %

**Comment by martindisley** [comment]
Thanks, I get I77 files for `Acoustic_guitar` (I don't think that's really a problem). But it's odd that my files, nearly identical to yours, should score so low? I'm sure there must be making an error somewhere (in my pipeline) because the files I've produced with my preprocessing have the same source and file structure. 

I've not edited `train.py` at all and can reproduce the results with you mention (~90%) with your files and preprocessing. But if I point `train.py` at another directory of [nearly identical files](https://drive.google.com/file/d/1wVT3WqF7CVhCkYwYOUtH-dyQiv5U4Y13/view?usp=sharing) it scores about (10%).

**Comment by seth814** [comment]
I think I fixed it. Can you `git pull` and try training again on your cleaned files? It's actually a dtype issue although I'm not sure why this fixes it. The output from kapre is the same regardless of dtype.

**Comment by martindisley** [comment]
Works perfectly now! Thanks for making those changes. This repo and the videos are a really great resource.

**Comment by martindisley** [comment]
Thanks for making those changes. After a `git pull`, `train.py` seems to work as expected. I think, however, I've got similar issues with `predict.py`. When pointing `predict.py` at `wavfiles` nearly everything comes out as 'Flute'. The model was up to  ~85% val accuracy in training.

In `predict.py` if I remove `dtype=np.float32` from here - `X_batch = np.array(batch, dtype=np.float32)` - I get the same output?

**Comment by martindisley** [comment]
I might have fixed it.

Switching `np.float32` instead, line 39 becomes.
`tmp = np.zeros(shape=(1,step), dtype=np.float32)`

This seems to have solved the issues on my end. You probably won't run into it as it's caused by amendments I've made to  `downsample_mono()` and `envelope()`

**Comment by seth814** [comment]
Oh whoops. Yeah I changed the wrong line. Should have been line 39.

**Comment by martindisley** [comment]
No worries, thanks for making the code public and documenting it with the videos. It's a great resource!
