### ISSUE TITLE
jypyter run !python clean.py only audio file not found for sub string: 3a3d0279 is displayed #84

### ISSUE THREAD

**Issue by Deep-learning999** [seth814/Audio-Classification#32]
jypyter run !python clean.py only audio file not found for sub string: 3a3d0279 is displayed #84
![Screenshot_20200817_134031](https://user-images.githubusercontent.com/64831773/90361505-fa736380-e090-11ea-871a-1fcf874cd969.jpg)

**Comment by seth814** [comment]
This would mean that the substring "3a3d0279" is not found in the src_directory. So src_root is either pointing to the wrong data or you need to change the filename you are searching for. clean.py is meant to either test_threshold to visualize signal envelope or you can comment that out and run split_wavs to clean all the data at src_root using the threshold value.

**Comment by Deep-learning999** [comment]
thanks
