### ISSUE TITLE
Can you update the code with kapre3.0? I feel that the change of kapre3.0 is very large, especially get_ melspectrogram_ Layer and Melspectrogram are very different

### ISSUE THREAD

**Issue by Deep-learning999** [seth814/Audio-Classification#33]
def Conv1D(N_CLASSES=6, SR=16000, DT=0.5):
    i = layers.Input(shape=(1, int(SR*DT)), name='input')
    x = Melspectrogram(n_dft=512, n_hop=160,
                       padding='same', sr=SR, n_mels=128,
                       fmin=0.0, fmax=SR/2, power_melgram=2.0,
                       return_decibel_melgram=True, trainable_fb=False,
                       trainable_kernel=False,
                       name='melbands')(i)

**Comment by davidwdw** [comment]
Having the same issue here...

**Comment by seth814** [comment]
Took a look at this today. The code should be updated to use kapre==0.3.4.
