### ISSUE TITLE
Model Predict Error

### ISSUE THREAD

**Issue by morgan-audibleai** [seth814/Audio-Classification#36]
Hi Seth, 

wonderful and really useful project and videos! I love it.

I am working on predicting on the original files as you finish with in the video however, when I do so, I get the following error:
"local variable 'batch_outputs' referenced before assignment"

After some quick research, this is due to the batch actually being an empty array and the error shows here:
X_batch = np.array(batch, dtype=np.float32)
y_pred = model.predict(X_batch)

since X_batch is made off of the batch array and when Y is trying to predict it throws the error. 

I tried with my original data that trained just fine and I also tried this with a singular file and got the same issue. 

Any ideas or is this on my end?

Thank you!

**Comment by seth814** [comment]
Can you send me the file you are trying to predict? I just need the one file that causes the error.
seth8141@gmail.com

Someone else had an issue with this. I've just never ran into with my files.

**Comment by seth814** [comment]
One file was actually an mp3 with wav extension. I deleted that file. Also switching from scipy's wavfile library to wavio was able to handle some of the errors that came up while initially cleaning the files. I think it just came down to some weird wavfiles that had something wrong with them. wavio seems to do a better job reading those.

I was not able to re-create the error with the file you sent. The errors occurred in the cleaning process and not prediction.

**Comment by seth814** [comment]
Switched to using wavio library. It ended up handling different files better than scipy. Issue has been sitting open. Closing.
