### ISSUE TITLE
Using from google colab notebook

### ISSUE THREAD

**Issue by Simiso-Gwala** [seth814/Audio-Classification#38]
Good day Seth,

I have been going over your work and as I am about to import the libraries, the code throws an import error, "cannot import name 'downsample_mono'." I am not sure which version of the 'clean' library did you import but could you kindly assist me in solving this error?
I am using Google Colab so I could utilize the GPU.

Thank you for supplying us with such, we are really grateful for it. Thank you for your time.
![screenshot_20201024_020255](https://user-images.githubusercontent.com/62940871/97062916-567ccb80-159d-11eb-97bd-07c1a2dcca12.png)

**Comment by seth814** [comment]
I downloaded the code to my google drive and mounted to the notebook instance.
You need to uncomment and install the requirements.txt.
I've never attempted to run this stuff from colab, but technically it could work. I did get a lot of warning when installing requirements.txt, so just might just want to install things one by one as you need them.
sys.path.append adds the mounted instance into PYTHONPATH, so you can make imports from clean.py.

![Screenshot from 2020-10-24 11-27-12](https://user-images.githubusercontent.com/17873279/97085528-0547f880-15ec-11eb-843b-8a364fe96f45.png)

**Comment by Simiso-Gwala** [comment]
Thank you very muxh for your help and swift response. 
Just one last point which I have to resolve. 

When I am running the prediction code I get thrown into this error: "Exception: Data must be 1-dimensional." Is there a way to solve this error which you could share with me.

**Comment by seth814** [comment]
I never tested this in google colab, so I'm not going to attempt to solve some error with data I don't have access to running in an instance that requires all the packages to be revised.
