### ISSUE TITLE
Error: Unknown Format: 3

### ISSUE THREAD

**Issue by Simiso-Gwala** [seth814/Audio-Classification#39]
Good day again Seth,

I have uploaded my own data wavfiles and when I try to clean the wave files using the clean.py code I get this error; “Error: unknown format: 3.” Is there a solution which you could provide so I can execute the cleaning process without this recurring error?

Looking forward to your feedback.
![91D5F7DE-924F-4861-8A32-8A8F2C482D5F](https://user-images.githubusercontent.com/62940871/97155947-b5e60180-177e-11eb-8b40-93778dd31310.jpeg)

**Comment by seth814** [comment]
I don't know. Probably just has something to do with the type of files you are using.

https://stackoverflow.com/questions/60352850/wave-error-unknown-format-3-arises-when-trying-to-convert-a-wav-file-into-text

**Comment by Simiso-Gwala** [comment]
Okay. Again, thank you for your aid, I will try and find means to resolve this.
