### ISSUE TITLE
downsample_mono method results in ValueError and y variable from Pandas Series results in Exception

### ISSUE THREAD

**Issue by fnandoz21** [seth814/Audio-Classification#40]
When I run the code as is, I first get an error that seems like it has something to do with the data not liking being downsampled to 16000:

"ValueError: Input signal length=1 is too small to resample from 44100->16000"

After commenting out line 36, I then get an error in line 15:

Exception: Data must be 1-dimensional

I fixed this by reshaping the y variable using this code:
`y = pd.Series(np.reshape(y, (len(y),))).apply(np.abs)`

I know someone else got their version of the repo to work without making any changes and that was on a Mac. Perhaps since I'm on Windows, there is some inconsistency?

**Comment by seth814** [comment]
Did you downsample your audio first? Actually what scripts are you running?

**Comment by Vladislav2018** [comment]
I have the sane error in this metod:

This is my stacktrace:

Traceback (most recent call last):
  File "D:\prog\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\prog\PyCharm Community Edition 2020.2.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 192, in <module>
    split_wavs(args)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 130, in split_wavs
    rate, wav = downsample_mono(src_fn, args.sr)
  File "D:/prog/Audio-Classification-master/Audio-Classification-master/clean.py", line 96, in downsample_mono
    wav = resample(wav, rate, sr)
  File "D:\prog\datascience\anaconda\lib\site-packages\librosa\core\audio.py", line 584, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "D:\prog\datascience\anaconda\lib\site-packages\resampy\core.py", line 97, in resample
    raise ValueError('Input signal length={} is too small to '
ValueError: Input signal length=1 is too small to resample from 81920->16000

This is a debug information of normal file that resamples successfully:
[This is a debug information of normal file that resamples successfully](https://user-images.githubusercontent.com/35165941/98393836-eb39fb80-206a-11eb-88e6-2480e831acd9.png)

[This is a debug information of problem file](https://user-images.githubusercontent.com/35165941/98393628-9bf3cb00-206a-11eb-84f9-0d4ed8349f5e.png)

**Comment by seth814** [comment]
This error actually makes no sense. If you look at the source code, this is raised when list(wav.shape)[-1] is less than 1, which it is not. It is 1, so I have no idea why it would raise in the first place.

@Vladislav2018 Can you send me the file that causes the error? I can try to figure something out.
seth8141@gmail.com

**Comment by seth814** [comment]
Took a closer look. I think I have figured out the issue. This should be fixed with the latest commit. If someone could check and verify everything is working that would be very helpful.

**Comment by Vladislav2018** [comment]
Yes, it works correctly. Thank you.

**Comment by seth814** [comment]
Going to close this. Gotten confirmation from 2 people it is working. This error was an issue with to_mono expecting a (2, n) or (n,) shape array.

**Comment by fnandoz21** [comment]
Sorry, yes I meant to comment that everything works without any additional editing now. Thanks for fixing this so promptly.
