### ISSUE TITLE
Python and Wav files - error 65534

### ISSUE THREAD

**Issue by coolio51** [seth814/Audio-Classification#41]
Hi Seth,

This is a Python issue but...I have a large audio collection that I am processing using your codes. For some of my files, I get this:
wave.Error: unknown format: 65534

I opened one of the files in Audicity, saved it as a 16-bit PCM and ran your codes again. It worked!
I have thousands of files so it's not practical to modify each of them. Is there anything that could be done directly from your codes?

Thanks

**Comment by seth814** [comment]
See #14 

This seems to be the cause: https://stackoverflow.com/questions/29000788/large-wave-file-not-being-read-in-python

You will likely need to convert your wav files. I would recommend using ffmpeg.
I posted a ffmpeg command in that issue that might work. Not sure though.

**Comment by coolio51** [comment]
I do not see the ffmpeg command you have posted 

but I found [https://online-audio-converter.com/](url) to be very useful in converting large number of files.

I'll test it out and let you know the outcome.

**Comment by coolio51** [comment]
My mistake. #14 has all the info necessary. I'm closing this issue.
Thanks
