### ISSUE TITLE
tqdm evaluation number - What does the '72' stand for?

### ISSUE THREAD

**Issue by coolio51** [seth814/Audio-Classification#42]
Not really an issue, but...

I'm running your tutorial. Could you tell me what this number represents: "72" (see picture)?
It's from the train.py using your data. I couldn't figure out where it comes from and how to modify it.

![image](https://user-images.githubusercontent.com/46771715/103446771-55170000-4cbe-11eb-9678-94a088c45d89.png)

**Comment by seth814** [comment]
That would be n_samples / batch_size for total batches in one epoch.
