### ISSUE TITLE
Can we detect  instruments  list from a song?

### ISSUE THREAD

**Issue by imiskolee** [seth814/Audio-Classification#63]
Hi,all:

it's supported split instrument from a  mixed sound?

input: WAV song

output:
   WAV of instrument 1:
   WAV of instrument 2:

or just detect instrument tag:

  instruments: ["Piano","Guitar","Double Bass"]

**Comment by seth814** [comment]
That is called source separation. You should use spleeter or demucs for source separation.
This model does classification or multi classification if you use a sigmoid activation at the output layer.
