### ISSUE TITLE
What is the source of our dataset?

### ISSUE THREAD

**Issue by HCIMaker** [seth814/Audio-Classification#68]
I am just curious what is the origin of our dataset? It is collected from Youtube Video or somewhere other?

**Comment by seth814** [comment]
The audio was originally pulled from one of the Freesound Audio Tagging competitions.
I only see a 2019 competition, but I thought it was from 17 or 18.
Either way, it's a good dataset. https://www.kaggle.com/competitions/freesound-audio-tagging-2019/overview

**Comment by HCIMaker** [comment]
> The audio was originally pulled from one of the Freesound Audio Tagging competitions. I only see a 2019 competition, but I thought it was from 17 or 18. Either way, it's a good dataset. https://www.kaggle.com/competitions/freesound-audio-tagging-2019/overview

OK! Thank you very much!
