### ISSUE TITLE
Version Mismatching

### ISSUE THREAD

**Issue by DonRichards** [seth814/Audio-Classification#8]
Just went through your video and got this error when pip installing

<img width="1186" alt="Screen Shot 2020-03-06 at 2 38 02 PM" src="https://user-images.githubusercontent.com/2738244/76116537-29e95480-5fb8-11ea-9ed4-b5bba3b650b6.png">

I assume this is caused by Tensorflow version? 

BTW, Thanks for the tutorials

**Comment by seth814** [comment]
Are you installing in a clean anaconda environment? This looks like tensorflow 2 is either already installed or tensorflow 2 is in the requirements.txt which it shouldn't be. I was able to recreate the tensorflow errors by first `pip install tensorflow==2`. It also looks like you have something else called astroid installed before as well.

Interestingly, you can run python and `print(tensorflow.__version__)` and my env is 1.15.2 which is correct despite tensorflow 2.0 being in there as well.

I don't get this error with a fresh conda env. After `conda create -n audio python=3.7`

`conda activate audio`
`pip list`

I have:

```
certifi    2019.11.28         
pip        20.0.2             
setuptools 45.2.0.post20200210
wheel      0.34.2
```

**Comment by DonRichards** [comment]
I'm not completely sure how I got it to work. Possibly using Spyder3 fixed the issue.
