### ISSUE TITLE
Missing Files Related to YouTube Tutorials Part by Part

### ISSUE THREAD

**Issue by E-B-Manohar** [seth814/Audio-Classification#9]
Hi, 
I See that you are updating the repo., grate

ful for your efforts.
I'm not able to find docx and instruments.csv file related pt.2 video.
Could you please try to arrange the files part by part as mentioned in the youtube.
ref:
![Capture](https://user-images.githubusercontent.com/45871357/80477808-319af900-896a-11ea-9ab4-1e427814d11a.PNG)

Thanks

**Comment by seth814** [comment]
`git checkout 404f2a6f989cec3421e8217d71ef070f3593a84d`

To restore to the commit from March 4th, 2020

Does that work for you?

**Comment by E-B-Manohar** [comment]
Thanks, I'll have to learn how to use "git commands"
